### PR TITLE
{2023.06}[foss/2022b] R v4.2.2

### PR DESCRIPTION
**Pull request by TopRichard**
Trying to add R/4.2.2 to software.eessi.io/2023.06.

Missing modules:
```
63 out of 137 required modules missing:

* libxslt/1.1.37-GCCcore-12.2.0 (libxslt-1.1.37-GCCcore-12.2.0.eb)
* nettle/3.8.1-GCCcore-12.2.0 (nettle-3.8.1-GCCcore-12.2.0.eb)
* jbigkit/2.1-GCCcore-12.2.0 (jbigkit-2.1-GCCcore-12.2.0.eb)
* Xvfb/21.1.6-GCCcore-12.2.0 (Xvfb-21.1.6-GCCcore-12.2.0.eb)
* Tk/8.6.12-GCCcore-12.2.0 (Tk-8.6.12-GCCcore-12.2.0.eb)
* libdeflate/1.15-GCCcore-12.2.0 (libdeflate-1.15-GCCcore-12.2.0.eb)
* LibTIFF/4.4.0-GCCcore-12.2.0 (LibTIFF-4.4.0-GCCcore-12.2.0.eb)
* NLopt/2.7.1-GCCcore-12.2.0 (NLopt-2.7.1-GCCcore-12.2.0.eb)
* libogg/1.3.5-GCCcore-12.2.0 (libogg-1.3.5-GCCcore-12.2.0.eb)
* FLAC/1.4.2-GCCcore-12.2.0 (FLAC-1.4.2-GCCcore-12.2.0.eb)
* libvorbis/1.3.7-GCCcore-12.2.0 (libvorbis-1.3.7-GCCcore-12.2.0.eb)
* UDUNITS/2.2.28-GCCcore-12.2.0 (UDUNITS-2.2.28-GCCcore-12.2.0.eb)
* libopus/1.3.1-GCCcore-12.2.0 (libopus-1.3.1-GCCcore-12.2.0.eb)
* Szip/2.1.1-GCCcore-12.2.0 (Szip-2.1.1-GCCcore-12.2.0.eb)
* GSL/2.7-GCC-12.2.0 (GSL-2.7-GCC-12.2.0.eb)
* LAME/3.100-GCCcore-12.2.0 (LAME-3.100-GCCcore-12.2.0.eb)
* libsndfile/1.2.0-GCCcore-12.2.0 (libsndfile-1.2.0-GCCcore-12.2.0.eb)
* GLPK/5.0-GCCcore-12.2.0 (GLPK-5.0-GCCcore-12.2.0.eb)
* LittleCMS/2.14-GCCcore-12.2.0 (LittleCMS-2.14-GCCcore-12.2.0.eb)
* MPFR/4.2.0-GCCcore-12.2.0 (MPFR-4.2.0-GCCcore-12.2.0.eb)
* ATK/2.38.0-GCCcore-12.2.0 (ATK-2.38.0-GCCcore-12.2.0.eb)
* GEOS/3.11.1-GCC-12.2.0 (GEOS-3.11.1-GCC-12.2.0.eb)
* Gdk-Pixbuf/2.42.10-GCCcore-12.2.0 (Gdk-Pixbuf-2.42.10-GCCcore-12.2.0.eb)
* PCRE/8.45-GCCcore-12.2.0 (PCRE-8.45-GCCcore-12.2.0.eb)
* FriBidi/1.0.12-GCCcore-12.2.0 (FriBidi-1.0.12-GCCcore-12.2.0.eb)
* at-spi2-core/2.46.0-GCCcore-12.2.0 (at-spi2-core-2.46.0-GCCcore-12.2.0.eb)
* Pango/1.50.12-GCCcore-12.2.0 (Pango-1.50.12-GCCcore-12.2.0.eb)
* libgit2/1.5.0-GCCcore-12.2.0 (libgit2-1.5.0-GCCcore-12.2.0.eb)
* at-spi2-atk/2.38.0-GCCcore-12.2.0 (at-spi2-atk-2.38.0-GCCcore-12.2.0.eb)
* HDF5/1.14.0-gompi-2022b (HDF5-1.14.0-gompi-2022b.eb)
* netCDF/4.9.0-gompi-2022b (netCDF-4.9.0-gompi-2022b.eb)
* libepoxy/1.5.10-GCCcore-12.2.0 (libepoxy-1.5.10-GCCcore-12.2.0.eb)
* GTK3/3.24.35-GCCcore-12.2.0 (GTK3-3.24.35-GCCcore-12.2.0.eb)
* Ghostscript/10.0.0-GCCcore-12.2.0 (Ghostscript-10.0.0-GCCcore-12.2.0.eb)
* ImageMagick/7.1.0-53-GCCcore-12.2.0 (ImageMagick-7.1.0-53-GCCcore-12.2.0.eb)
* googletest/1.12.1-GCCcore-12.2.0 (googletest-1.12.1-GCCcore-12.2.0.eb)
* nlohmann_json/3.11.2-GCCcore-12.2.0 (nlohmann_json-3.11.2-GCCcore-12.2.0.eb)
* PROJ/9.1.1-GCCcore-12.2.0 (PROJ-9.1.1-GCCcore-12.2.0.eb)
* libgeotiff/1.7.1-GCCcore-12.2.0 (libgeotiff-1.7.1-GCCcore-12.2.0.eb)
* hypothesis/6.68.2-GCCcore-12.2.0 (hypothesis-6.68.2-GCCcore-12.2.0.eb)
* libtirpc/1.3.3-GCCcore-12.2.0 (libtirpc-1.3.3-GCCcore-12.2.0.eb)
* HDF/4.2.15-GCCcore-12.2.0 (HDF-4.2.15-GCCcore-12.2.0.eb)
* CFITSIO/4.2.0-GCCcore-12.2.0 (CFITSIO-4.2.0-GCCcore-12.2.0.eb)
* gfbf/2022b (gfbf-2022b.eb)
* Boost/1.81.0-GCC-12.2.0 (Boost-1.81.0-GCC-12.2.0.eb)
* Eigen/3.4.0-GCCcore-12.2.0 (Eigen-3.4.0-GCCcore-12.2.0.eb)
* giflib/5.2.1-GCCcore-12.2.0 (giflib-5.2.1-GCCcore-12.2.0.eb)
* arpack-ng/3.8.0-foss-2022b (arpack-ng-3.8.0-foss-2022b.eb)
* Catch2/2.13.9-GCCcore-12.2.0 (Catch2-2.13.9-GCCcore-12.2.0.eb)
* Armadillo/11.4.3-foss-2022b (Armadillo-11.4.3-foss-2022b.eb)
* pybind11/2.10.3-GCCcore-12.2.0 (pybind11-2.10.3-GCCcore-12.2.0.eb)
* SciPy-bundle/2023.02-gfbf-2022b (SciPy-bundle-2023.02-gfbf-2022b.eb)
* json-c/0.16-GCCcore-12.2.0 (json-c-0.16-GCCcore-12.2.0.eb)
* Xerces-C++/3.2.4-GCCcore-12.2.0 (Xerces-C++-3.2.4-GCCcore-12.2.0.eb)
* Imath/3.1.6-GCCcore-12.2.0 (Imath-3.1.6-GCCcore-12.2.0.eb)
* OpenEXR/3.1.5-GCCcore-12.2.0 (OpenEXR-3.1.5-GCCcore-12.2.0.eb)
* Qhull/2020.2-GCCcore-12.2.0 (Qhull-2020.2-GCCcore-12.2.0.eb)
* Highway/1.0.3-GCCcore-12.2.0 (Highway-1.0.3-GCCcore-12.2.0.eb)
* Brunsli/0.1-GCCcore-12.2.0 (Brunsli-0.1-GCCcore-12.2.0.eb)
* LERC/4.0.0-GCCcore-12.2.0 (LERC-4.0.0-GCCcore-12.2.0.eb)
* OpenJPEG/2.5.0-GCCcore-12.2.0 (OpenJPEG-2.5.0-GCCcore-12.2.0.eb)
* GDAL/3.6.2-foss-2022b (GDAL-3.6.2-foss-2022b.eb)
* R/4.2.2-foss-2022b (R-4.2.2-foss-2022b.eb)

```

### CODE REVIEW

**Comment by TopRichard** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/generic

**Comment by bedroge** [comment]
This depends on / has a significant overlap with #419 and #448, so it's probably best to wait till those have been merged.

**Comment by bedroge** [comment]
> This depends on / has a significant overlap with:
> 
> * #419
> 
> * #448 
> 
> 
> 
> so it's probably best to wait till those have been merged.

@TopRichard Those two PRs have been merged, so you can try this one now.

**Comment by boegel** [comment]
merge conflict should be fixed first

**Comment by TopRichard** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/generic

**Comment by bedroge** [comment]
Now ImageMagick is failing with similar issues as in #428:
```
/cvmfs/software.eessi.io/versions/2023.06/compat/linux/x86_64/usr/bin/ld: warning: libfribidi.so.0, needed by /cvmfs/software.eessi.io/versions/2023.06/s
oftware/linux/x86_64/generic/software/Pango/1.50.12-GCCcore-12.2.0/lib64/libpango-1.0.so, not found (try using -rpath or -rpath-link)
/cvmfs/software.eessi.io/versions/2023.06/compat/linux/x86_64/usr/bin/ld: /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/generic/software/Pango/1.50.12-GCCcore-12.2.0/lib64/libpango-1.0.so: undefined reference to `fribidi_get_par_embedding_levels_ex'
/cvmfs/software.eessi.io/versions/2023.06/compat/linux/x86_64/usr/bin/ld: /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/generic/software/Pango/1.50.12-GCCcore-12.2.0/lib64/libpango-1.0.so: undefined reference to `fribidi_get_bidi_type'
/cvmfs/software.eessi.io/versions/2023.06/compat/linux/x86_64/usr/bin/ld: /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/generic/software/Pango/1.50.12-GCCcore-12.2.0/lib64/libpango-1.0.so: undefined reference to `fribidi_get_bracket'
```

**Comment by bedroge** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/generic

**Comment by bedroge** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen3

**Comment by bedroge** [comment]
bot: build repo:eessi.io-2023.06-software arch:aarch64/generic
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_n1
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_v1
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen2
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/haswell
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/skylake_avx512

**Comment by bedroge** [comment]
> New job on instance `eessi-bot-mc-aws` for architecture `aarch64-neoverse_v1` for repository `eessi.io-2023.06-software` in job dir `/project/def-users/SHARED/jobs/2024.03/pr_452/7624`
> 
> date	job status	comment
> Mar 12 19:36:20 UTC 2024	submitted	job id `7624` awaits release by job manager
> Mar 12 19:37:05 UTC 2024	released	job awaits launch by Slurm scheduler
> Mar 12 19:38:19 UTC 2024	running	job `7624` is running
> Mar 12 23:33:36 UTC 2024	finished	
> 😢 FAILURE _(click triangle for details)_
> Mar 12 23:33:36 UTC 2024	test result	_(no tests yet)_

Seems like we're almost there, but the Arm builds (at least the one for `neoverse_v1`) failed at `dbarts 0.9-23 (929/1197)...` with a whole bunch of the following errors:
```
   16 |   uint8x16_t vmask = vandq_u8(input, vdupq_n_u8(0x80));
      |   ^~~~~~~~~~
partition_neon.c:16:31: error: incompatible type for argument 1 of vandq_u8
   16 |   uint8x16_t vmask = vandq_u8(input, vdupq_n_u8(0x80));
      |                               ^~~~~
      |                               |
      |                               uint16x8_t
In file included from ../include/misc/intrinsic.h:9,
                 from partition_neon.c:8:
/cvmfs/software.eessi.io/versions/2023.06/software/linux/aarch64/neoverse_v1/software/GCCcore/12.2.0/lib/gcc/aarch64-unknown-linux-gnu/12.2.0/include/arm_neon.h:1120:22: note: expected uint8x16_t but argument is of type uint16x8_t
 1120 | vandq_u8 (uint8x16_t __a, uint8x16_t __b)
      |           ~~~~~~~~~~~^~~
partition_neon.c:19:27: error: incompatible type for argument 2 of vshlq_u8
   19 |   vmask = vshlq_u8(vmask, vshift);
      |                           ^~~~~~
      |                           |
      |                           uint8x16_t
/cvmfs/software.eessi.io/versions/2023.06/software/linux/aarch64/neoverse_v1/software/GCCcore/12.2.0/lib/gcc/aarch64-unknown-linux-gnu/12.2.0/include/arm_neon.h:23830:37: note: expected int8x16_t but argument is of type uint8x16_t
23830 | vshlq_u8 (uint8x16_t __a, int8x16_t __b)
      |                           ~~~~~~~~~~^~~
In file included from partition_neon.c:29:
partition_body.c: In function misc_partitionRange_neon:
partition_body.c:147:38: error: incompatible type for argument 1 of vmovemask_u8
  147 | #  define movemask(_X_) vmovemask_u8(vreinterpretq_u8_u16(_X_))
      |                                      ^~~~~~~~~~~~~~~~~~~~~~~~~
      |                                      |
      |                                      uint8x16_t
```

**Comment by boegel** [comment]
@bedroge Looks very similar to https://github.com/ggerganov/llama.cpp/issues/949 (but different software), seems like we'll need a patch?
Maybe start with reporting the issue via https://github.com/vdorie/dbarts/blob/main/src/misc/partition_neon.c, repo seems pretty active...

**Comment by bedroge** [comment]
Opened an issue: https://github.com/vdorie/dbarts/issues/66

**Comment by bedroge** [comment]
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_v1

**Comment by bedroge** [comment]
`
bot: build repo:eessi.io-2023.06-software arch:aarch64/generic
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_n1
bot: build repo:eessi.io-2023.06-software arch:x86_64/generic
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen2
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen3
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/haswell
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/skylake_avx512

**Review by bedroge — APPROVED** [review]
