### PR TITLE
{2023.06}[foss/2021b] matplotlib v3.4.3

### PR DESCRIPTION
**Pull request by laraPPr**
* Qhull/2020.2-GCCcore-11.2.0 (Qhull-2020.2-GCCcore-11.2.0.eb)
* cppy/1.1.0-GCCcore-11.2.0 (cppy-1.1.0-GCCcore-11.2.0.eb)
* Pillow/8.3.2-GCCcore-11.2.0 (Pillow-8.3.2-GCCcore-11.2.0.eb)
* Tkinter/3.9.6-GCCcore-11.2.0 (Tkinter-3.9.6-GCCcore-11.2.0.eb)
* matplotlib/3.4.3-foss-2021b (matplotlib-3.4.3-foss-2021b.eb)

### CODE REVIEW

**Comment by laraPPr** [comment]
bot:build repo:eessi-2023.06-software arch:x86_64/generic

**Comment by laraPPr** [comment]
bot: build repo:eessi-2023.06-software arch:x86_64/generic

**Comment by laraPPr** [comment]
ERROR: Command errored out with exit status 1: /cvmfs/pilot.eessi-hpc.org/versions/2023.06/software/linux/x86_64/generic/software/Python/3.9.6-GCCcore-11.2.0/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/eb-gxasriu9/eb-qrb30k5v/eb-klv0wyfj/eb-qd7tx8ww/pip-req-build-1s21bwfi/setup.py'"'"'; __file__='"'"'/tmp/eb-gxasriu9/eb-qrb30k5v/eb-klv0wyfj/eb-qd7tx8ww/pip-req-build-1s21bwfi/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/eb-gxasriu9/eb-qrb30k5v/eb-klv0wyfj/eb-qd7tx8ww/pip-record-igyea73l/install-record.txt --single-version-externally-managed --prefix /cvmfs/pilot.eessi-hpc.org/versions/2023.06/software/linux/x86_64/generic/software/Pillow/8.3.2-GCCcore-11.2.0 --compile --install-headers /cvmfs/pilot.eessi-hpc.org/versions/2023.06/software/linux/x86_64/generic/software/Pillow/8.3.2-GCCcore-11.2.0/include/python3.9/Pillow Check the logs for full command output.

 (at easybuild/tools/run.py:681 in parse_cmd_output)

**Comment by boegel** [comment]
Actual build error for `Pillow-8.3.2-GCCcore-11.2.0.eb`:
```
    In file included from /cvmfs/pilot.eessi-hpc.org/versions/2023.06/software/linux/x86_64/generic/software/Python/3.9.6-GCCcore-11.2.0/include/python3.9/Python.h:25,
                     from src/Tk/../libImaging/ImPlatform.h:10,
                     from src/Tk/../libImaging/Imaging.h:13,
                     from src/Tk/tkImaging.c:42:
    /usr/include/stdio.h:781:10: fatal error: bits/sys_errlist.h: No such file or directory
      781 | #include <bits/sys_errlist.h>
          |          ^~~~~~~~~~~~~~~~~~~~
```

The `/usr/include/stdio.h` is the problem here, this should be coming from the compat layer rather than from the host OS.

It seems like these paths are hardcoded in `Pillow`, see https://github.com/python-pillow/Pillow/blob/main/setup.py#L608, but it seems like there's a `disable-platform-guessing` option available to disable this?

**Comment by laraPPr** [comment]
`
Build flag: -C platform-guessing=disable. Skips all of the platform dependent guessing of include and library directories for automated build systems that configure the proper paths in the environment variables (e.g. Buildroot).
`
https://pillow.readthedocs.io/en/stable/installation.html

**Comment by laraPPr** [comment]
https://github.com/easybuilders/easybuild-easyconfigs/pull/18881

**Comment by laraPPr** [comment]
bot:build repo:eessi-2023.06-software arch:x86_64/generic

**Comment by laraPPr** [comment]
bot: build repo:eessi-2023.06-software arch:x86_64/generic

**Comment by laraPPr** [comment]
bot: help

**Comment by laraPPr** [comment]
```
== 2023-10-03 09:29:25,858 build_log.py:171 ERROR EasyBuild crashed with an error (at easybuild/tools/build_log.py:111 in caller_info): Failed to get data for PR #18851 from easybuilders/easybuild-easyconfigs (HTTP Error 403: rate limit exceeded)

Please check PR #, account and repo. (at easybuild/tools/github.py:2411 in fetch_pr_data)
```

**Comment by laraPPr** [comment]
bot: build repo:eessi-2023.06-software arch:x86_64/generic

**Comment by laraPPr** [comment]
```
== 2023-10-03 11:45:00,709 build_log.py:171 ERROR EasyBuild crashed with an error (at easybuild/tools/build_log.py:111 in caller_info): Build of /tmp/eb-3qgb0teu/eb-hyhyto6j/eb-h04p81_x/eb-k5s_gwe_/files_pr18881/p/Pillow/Pillow-8.3.2-GCCcore-11.2.0.eb failed (err: 'build failed (first 300 chars): cmd " /cvmfs/pilot.eessi-hpc.org/versions/2023.06/software/linux/x86_64/generic/software/Python/3.9.6-GCCcore-11.2.0/bin/python -m pip install --prefix=/cvmfs/pilot.eessi-hpc.org/versions/2023.06/software/linux/x86_64/generic/software/Pillow/8.3.2-GCCcore-11.2.0 --global-option=build_ext --global-op') (at easybuild/main.py:175 in build_and_install_software)
```

**Comment by laraPPr** [comment]
There are more than one log file in `/mnt/shared/bot-build-logs/jobs/7684`:
- `easybuild-5p1lf80p.log` is related to ReFrame
``` 
== 2023-10-03 11:45:46,387 build_log.py:171 ERROR EasyBuild crashed with an error (at easybuild/tools/build_log.py:111 in caller_info): Failed to get data for PR #18851 from easybuilders/easybuild-easyconfigs (HTTP Error 403: rate limit exceeded)

Please check PR #, account and repo. (at easybuild/tools/github.py:2411 in fetch_pr_data)
```
- is related to OpenBlas
```
== 2023-10-03 11:45:42,364 build_log.py:171 ERROR EasyBuild crashed with an error (at easybuild/tools/build_log.py:111 in caller_info): Failed to get data for PR #18887 from easybuilders/easybuild-easyconfigs (HTTP Error 403: rate limit exceeded)

Please check PR #, account and repo. (at easybuild/tools/github.py:2411 in fetch_pr_data)
```
- ` easybuild-tb_c5rsa.log` is the actual log failed log for this pr

**Comment by boegel** [comment]
The actual build issue with `Pillow` now is that it can't find `zlib`:

```
    The headers or library files could not be found for zlib,
    a required dependency when compiling Pillow from source.
```

So we need to somehow instruct Pillow's `setup.py` to look for `zlib` into the compat layer.

This may mean patching the hardcoded paths to `/usr/include` in `setup.py`, and not using `--disable-platform-guessing` (which was introduced in https://github.com/easybuilders/easybuild-easyconfigs/pull/18881), or maybe just adding the appropriate paths to `$CPATH` and `$LIBRARY_PATH` via a hook:

```
CPATH=/cvmfs/pilot.eessi-hpc.org/versions/2023.06/compat/linux/x86_64/usr/include/
LIBRARY_PATH=/cvmfs/pilot.eessi-hpc.org/versions/2023.06/compat/linux/x86_64/usr/lib64
```

**Comment by boegel** [comment]
I've opened a support issue for the trouble with getting Pillow installed into EESSI: https://gitlab.com/eessi/support/-/issues/9

**Comment by TopRichard** [comment]
Check : #362

**Comment by laraPPr** [comment]
bot: build arch:x86_64/generic repo:eessi-hpc.org-2023.06-software

**Comment by laraPPr** [comment]
bot: build arch:x86_64/generic repo:eessi-hpc.org-2023.06-software

**Comment by laraPPr** [comment]
bot: show_config

**Comment by laraPPr** [comment]
bot: build arch:x86_64/intel/haswell repo:eessi-hpc.org-2023.06-software

**Comment by laraPPr** [comment]
bot: build arch:x86_64/intel/skylake_avx512 repo:eessi-hpc.org-2023.06-software
bot: build arch:x86_64/amd/zen2 repo:eessi-hpc.org-2023.06-software
bot: build arch:x86_64/amd/zen3 repo:eessi-hpc.org-2023.06-software
bot: build arch:aarch64/generic repo:eessi-hpc.org-2023.06-software
bot: build arch:aarch64/neoverse_n1 repo:eessi-hpc.org-2023.06-software
bot: build arch:aarch64/neoverse_v1 repo:eessi-hpc.org-2023.06-software

**Review by bedroge — APPROVED** [review]
